import type { Meta, StoryObj } from '@storybook/react-vite';
import { EmailBadge } from './EmailBadge';

/**
 * Story configuration for the EmailBadge component.
 * It demonstrates how the badge renders an icon, a custom label (provided by TaskText),
 * and maintains a functional mailto link.
 */
const meta: Meta<typeof EmailBadge> = {
  title: 'Components/CustomBadges/EmailBadge',
  component: EmailBadge,
  parameters: {
    layout: 'centered',
  },
  tags: ['autodocs'],
  argTypes: {
    email: {
      control: 'text',
      description: 'The real email address for the mailto link.',
    },
    label: {
      control: 'text',
      description: 'The display text (usually generated by TaskText, e.g., "Mail 1").',
    },
  },
};

export default meta;
type Story = StoryObj<typeof EmailBadge>;

/**
 * Common use case where TaskText provides a numbered label.
 */
export const NumberedLabel: Story = {
  args: {
    email: 'ezequiel@example.com',
    label: 'Mail 1',
  },
};

/**
 * Use case showing the component with the full email as label.
 */
export const FullEmailLabel: Story = {
  args: {
    email: 'contact@company.com',
    label: 'contact@company.com',
  },
};

/**
 * Example with a very long email to check layout stability.
 */
export const LongEmail: Story = {
  args: {
    email: 'very.long.email.address.for.testing.purposes@domain.org',
    label: 'Mail 99',
  },
};